# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


# This function returns the number at the specified index
# in the Fibonnaci sequence
def fibonnaci(index)
  if index <= 1
    return index
  else
    fibonnaci(index - 1) + fibonnaci(index - 2)
  end
end

i = 0
sum = 0
number = 0

while number < 4000000
  number = fibonnaci(i)
  if number % 2 == 0
    sum += number
  end
  i += 1
end

puts sum
