# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonnacci(index):
  if index <= 1:
    return index
  else:
    return fibonnacci(index - 1) + fibonnacci(index - 2)

num = 0
sumTotal = 0

while num < 4000000:
  # We don't want to run fib twice, so let's save it
  currentFibonnacciAnswer = fibonnacci(num)

  if currentFibonnacciAnswer % 2 == 0:
    sumTotal += currentFibonnacciAnswer
  # num += 1
  num = currentFibonnacciAnswer

print sumTotal